repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: f8d8c45220230434bd7440d85a7f64c67bcdb952
    hooks:
      - id: check-yaml
        exclude: ^(conda\.recipe/meta\.yaml|conda_build/templates/.*\.yaml|docs/click/meta\.yaml|conda/meta\.yaml|conda/construct.yaml|.*\.pic\.yml|conda/constructor/Miniforge3/construct.yaml)
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: d1248ca9beaf0ba526d265f4108836d89cf551b7
    hooks:
      - id: black
        # exclude: '^gdsfactory/samples/notebooks/|^docs/notebooks/'

  - repo: https://github.com/codespell-project/codespell
    rev: af69927c7d3965d3fe8f68007e12cd971847573f
    hooks:
      - id: codespell
        args: ["-L TE,TE/TM,te,ba,FPR,fpr_spacing,ro,nd,donot,schem,MATC"]
        additional_dependencies:
          - tomli

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "770e3ceae230e989c8337eb434b7707d5f796e3d"
    hooks:
      - id: ruff

  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: d2425a62376c2197448cce2f825d5a0c3926b862
    hooks:
      - id: pretty-format-toml
        args: [--autofix]

  - repo: https://github.com/aristanetworks/j2lint.git
    rev: 1f242682122fa258557e429f1b92fadd6d2be2d4
    hooks:
      - id: j2lint
        args: [--ignore, jinja-statements-delimiter, --]
