FROM quay.io/singularity/singularity:v3.10.4 as palace

WORKDIR /src
RUN wget https://raw.githubusercontent.com/awslabs/palace/main/singularity/singularity.def
RUN singularity build palace.sif singularity.def


FROM jupyter/base-notebook:python-3.10

# expose klive and Jupyter Notebook ports
EXPOSE 8082
EXPOSE 8083
EXPOSE 8888

USER root
RUN apt-get update --yes && \
    apt-get install --yes --no-install-recommends \
        make \
        git \
        python3-gmsh \
        htop \
        neovim \
        wget \
        software-properties-common \
        gnupg && \
    # Singularity for Palace
    wget https://github.com/apptainer/apptainer/releases/download/v1.2.2/apptainer_1.2.2_amd64.deb && \
    # Elmer
    apt-add-repository ppa:elmer-csc-ubuntu/elmer-csc-ppa && \
    apt-get update --yes && \
    apt-get install --yes --no-install-recommends elmerfem-csc ./apptainer_1.2.2_amd64.deb && \
    # Undo apt-get update for final image
    rm -rf /var/lib/apt/lists/* apptainer_1.2.2_amd64.deb

USER jovyan
RUN conda init bash

# Add Palace to PATH
COPY --from=build /src/palace.sif ~/palace.sif
RUN echo '#!/bin/bash' > ~/.local/bin/palace && \
    echo 'singularity exec ~/palace.sif /opt/palace/bin/palace "$@"' >> ~/.local/bin/palace && \
    chmod +x ~/.local/bin/palace

RUN mamba install gdspy gdstk pymeep=*=mpi_mpich_* -y && \
    mamba install -c conda-forge slepc4py=*=complex* -y


RUN pip install gdsfactory[cad,full]
WORKDIR /home/jovyan
